version: '2.4'

volumes:
  postgres-data: {}

# networks:
#   technicals:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.11.0.0/16
#     driver_opts:
#       com.docker.network.bridge.name: br_technicals

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKER_PATH/portainer-ce/data:/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # networks:
    #   technicals:
    #     ipv4_address: '172.11.0.110'

  fleetio:
    container_name: fleetio
    image: postgres
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      POSTGRES_DB: fleetio
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/fleetio
    restart: always
    volumes:
      - $DOCKER_PATH/postgres/etc:/etc/postgresql
      - $DOCKER_PATH/postgres/log:/var/log/postgresql
      - $DOCKER_PATH/postgres:/var/lib/postgresql
    ports:
      - 1234:5432
    # networks:
    #   technicals:
    #     ipv4_address: '172.11.0.111'

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels: 
      autoheal: $AUTOHEAL_RESTART
    restart: always
    # networks:
    #   technicals:
    #     ipv4_address: '172.11.0.112'


