version: '2.4'

volumes:
  postgres-data: {}

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKER_PATH/portainer-ce/data:/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      TZ: $TZ
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_POLL_INTERVAL: 10000
      WATCHTOWER_TIMEOUT: 15
    restart: always

  monocker:
    container_name: monocker
    image: petersem/monocker
    environment:
      MESSAGE_PLATFORM: $MONOCKER_MESSAGE_PLATFORM
      # Optional - includes or excludes specified containers - default behaviour is false
      LABEL_ENABLE: 'false'
      # Optional - only show when container state changes to being offline (paused, exited, running (unhealthy), or dead) - default is false
      ONLY_OFFLINE_STATES: 'false'
      # Optional - regardless of any other settings, you can ignore or include 'exited'
      EXCLUDE_EXITED: 'false'
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels: 
      autoheal: $AUTOHEAL_RESTART
    restart: always

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels: 
      autoheal: $AUTOHEAL_RESTART
    restart: always

  fleetio:
    container_name: fleetio
    image: postgres
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      POSTGRES_DB: fleetio
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/fleetio
    # restart: always
    volumes:
      - $DOCKER_PATH/postgres/etc:/etc/postgresql
      - $DOCKER_PATH/postgres/log:/var/log/postgresql
      - $DOCKER_PATH/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
